version: '2'
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: pern_client
    ports:
      - 3000:3000
    volumes:
      - ./client:/app
      - /app/node_modules #hot-reload
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    container_name: pern_server
    ports:
      - 3050:3050
    # networks:
    #   - pern-app
    # depends_on:
    #   - db
    volumes:
      - ./server:/app
      - /app/node_modules

  # db:
  #   image: postgres:15.2-alpine
  #   container_name: pern_db_postgres
  #   ports:
  #     - '5432:5432'
  #   networks:
  #     - pern-app
  #   volumes:
  #     - data:/data/db
  #   environment:
  #     - POSTGRES_PASSWORD=mysecretpassword
  #     - POSTGRES_DB=perntodo

# networks:
#   pern-app:
#     driver: bridge

# volumes:
#   data: {}

